version: "3.4"

services:
  indevche:
    image: indevche
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 3000:3000
